### ISSUE TITLE
UI wont load

### ISSUE THREAD

**Issue by Bllake** [VinegarYap/Monstercat-Desktop-Player#7]
having a slight issue where the player will go completely blank, just a white screen. So far its only happened once in about 70 hours of usage but I cant tell what caused it, however it happened on initial boot of the PC so maybe a connectivity issue? any help would be greatly appreciated!

**Comment by VinegarYap** [comment]
Hey there Bllake, it sounds like it could have been an initialization error with CefSharp or an error loading the website. Did relaunching the program and/or your computer fix the issue at all, or is it still ongoing? If so I can take a look and try to reproduce the issue and get a fix out.

**Comment by VinegarYap** [comment]
Sorry for the late update!

https://github.com/VinegarYap/Monstercat-Desktop-Player/releases/tag/v2.0.0
